version: "3.1"
services:
  rest-api:
    build:
     context: .
     dockerfile: Dockerfile
    restart: always
    ports:
      - ${API_PORT}:8080
    env_file:
      - .env.server
    links:
      - mysql-db
    volumes:
      - .:/home/rest-api:delegated
    command: make live
  mysql-db:
    image: mysql:8.0
    restart: always
    environment:    
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}      
    ports:
      - ${MYSQL_PORT}:3306